version: "3.5"

services:
  mysql:
    container_name: pupuga_mysql_7
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes: 
      - ${MYSQL_DATA}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  php:
    container_name: pupuga_host_7
    build: ./php
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on: 
      - mysql
    links:
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT_DIR}:/var/www/
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
  nginx:
    build:
      context: ./nginx
    image: "${COMPOSE_PROJECT_NAME}/nginx:${IMAGE_TAG}"
    hostname: "${COMPOSE_PROJECT_NAME}-nginx"
    ports:
      - "8081:80"
    volumes:
      - ..:/app:cached
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php
