version: "3.8"

services:
  mysql:
    container_name: pupuga_mysql
    build: ./servers/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes: 
      - ${MYSQL_DATA}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  server:
    container_name: pupuga_nginx
    build: ./servers/nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${DOCUMENT_ROOT_DIR}:/var/www/
      - ${NGINX_CONFIG}:./nginx/app.conf:/etc/nginx/conf.d/default.conf:cached
  php:
    container_name: pupuga_php-fpm
    build: ./servers/php-fpm
    volumes: 
      - ${PHP_INI}:/usr/local/etc/php/php.ini