version: "3.8"

services:
  mysql:
    container_name: mysqldb
    build: ./servers/mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  nodejs:
    container_name: nodejs
    build: ./servers/nodejs
    ports:
      - '80:8080'
  apache-php:
    container_name: apache-php
    build: ./servers/apache-php
    restart: always
#    extra_hosts:
#      - "win4win.loc:192.168.0.1"
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mysql
    links:
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT_DIR}:/var/www/
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${APACHE_VHOSTS}:/etc/apache2/sites-enabled/default.conf
      - ${LOG_DIR}:/var/log/
#  redis:
#    container_name: 'redis'
#    image: redis:latest
#    ports:
#      - '6379:6379'